#!/usr/bin/env bash
# .bashrc - This runs for every non-login interactive shell.

# We do pretty much all the work to configure our shell inside our rc file,
# this means some of the work will be duplicated for any given login session
# everytime a new non-login interactive shell is started. In practical terms I
# can't see this being a major issue.

# Define our path as early as possible
PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin";
PATH="$PATH:$HOME/.dart/current/bin";
PATH="$PATH:$HOME/.dotnet";
PATH="$PATH:$HOME/.goenv/bin";
PATH="$PATH:$HOME/.linuxbrew/bin";
PATH="$PATH:$HOME/.local/bin";
PATH="$PATH:$HOME/.nodenv/bin";
PATH="$PATH:$HOME/.pkenv/bin";
PATH="$PATH:$HOME/.pub-cache/bin";
PATH="$PATH:$HOME/.pyenv/bin";
PATH="$PATH:$HOME/.rbenv/bin";
PATH="$PATH:$HOME/.tfenv/bin";

# Source global definitions
[ -f /etc/bashrc ] && . /etc/bashrc;

# Setup the ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket";

# Standardise UID & GID, UID is normally set but GID is not.
# So we just do both here which makes writting scripts easier.
export UID="$(id -u)" &> /dev/null || true;
export GID="$(id -g)" &> /dev/null || true;

# Tell goenv where to install go, personally I prefer all my tools and
# config to be hidden (ie: start with a dot) and all my actual data
# folders/files to unhidden.
export GOENV_GOPATH_PREFIX="$HOME/.go";

# Configure aws-vault to use gopass to store our idenities
export AWS_VAULT_BACKEND="pass";
export AWS_VAULT_PASS_CMD="gopass";
export AWS_VAULT_PASS_PREFIX="aws-vault";
export AWS_VAULT_PASS_PASSWORD_STORE_DIR="$HOME/.password-store";

# Setup some bash auto completion
complete -C "$HOME/.local/bin/aws_completer" aws;
eval "$(aws-vault --completion-script-bash)";
eval "$(gopass completion bash)";

# Setup all our tool version managers
source "$HOME/.sdkman/bin/sdkman-init.sh";
eval "$(brew shellenv)";
eval "$(nodenv init -)";
eval "$(pyenv init -)";
eval "$(rbenv init -)";
eval "$(goenv init -)";
PATH="$PATH:$GOROOT/bin";
PATH="$PATH:$GOPATH/bin";

# We have some scripts which add additional funcitonality to existing tools
PATH="$HOME/.local/sbin/bin:$PATH";

# Rdp shortcuts fro Xero Pod Servers
alias rdp-bastion-xero-payroll-test="rdp -g 'rdgw-test.xero-support.com' -h 'msrds.vpc-94dd34f0.inbound.xero-support.com' -u 'XOAWSMAN\brad.jones' -p '$(gopass websites/xero.okta.com/brad.jones@xero.com)'";
alias rdp-pod1="rdp --profile xero-payroll-test --ec2 podserver-pod1-B26-branch4 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod2="rdp --profile xero-payroll-test --ec2 podserver-pod2-B40-branch15 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod3="rdp --profile xero-payroll-test --ec2 podserver-pod3-B44-branch44 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod4="rdp --profile xero-payroll-test --ec2 podserver-pod4-B18-branch48 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod5="rdp --profile xero-payroll-test --ec2 podserver-pod5-B30-pod5 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod6="rdp --profile xero-payroll-test --ec2 podserver-pod6-B34-branch4 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod7="rdp --profile xero-payroll-test --ec2 podserver-pod7-B94-branch4 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod8="rdp --profile xero-payroll-test --ec2 podserver-pod8-B32-branch44 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod9="rdp --profile xero-payroll-test --ec2 podserver-pod9-B29-branch48 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod10="rdp --profile xero-payroll-test --ec2 podserver-pod10-B81-branch4 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod11="rdp --profile xero-payroll-test --ec2 podserver-pod11-B14-branch4 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod12="rdp --profile xero-payroll-test --ec2 podserver-pod12-B76-branch44 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod13="rdp --profile xero-payroll-test --ec2 podserver-pod13-B11-branch44 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod15="rdp --profile xero-payroll-test --ec2 podserver-pod15-B3-branch4 --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem";
alias rdp-pod16='rdp --profile xero-payroll-test --ec2 "podserver-pod16-B33-<default>" --key ~/.ssh/keys/xero-payroll-test/payroll-devops.pem';
alias rdp-pod1-db="rdp --profile xero-payroll-test --ec2 pod1-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod2-db="rdp --profile xero-payroll-test --ec2 pod2-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod3-db="rdp --profile xero-payroll-test --ec2 pod3-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod4-db="rdp --profile xero-payroll-test --ec2 pod4-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod5-db="rdp --profile xero-payroll-test --ec2 pod5-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod6-db="rdp --profile xero-payroll-test --ec2 pod6-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod7-db="rdp --profile xero-payroll-test --ec2 pod7-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod8-db="rdp --profile xero-payroll-test --ec2 pod8-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod9-db="rdp --profile xero-payroll-test --ec2 pod9-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod10-db="rdp --profile xero-payroll-test --ec2 pod10-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod11-db="rdp --profile xero-payroll-test --ec2 pod11-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod12-db="rdp --profile xero-payroll-test --ec2 pod12-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod13-db="rdp --profile xero-payroll-test --ec2 pod13-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod15-db="rdp --profile xero-payroll-test --ec2 pod15-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";
alias rdp-pod16-db="rdp --profile xero-payroll-test --ec2 pod16-db-instance --key ~/.ssh/keys/xero-payroll-test/payroll-dev-public.pem";