#!/usr/bin/env bash
# .env - Set all simple (key:value) environment variables here.
# The PATH should be set in .path to ensure it is idempotent.

# Setup the ssh-agent
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket";

# Standardise UID & GID, UID is normally set but GID is not.
# So we just do both here which makes writting scripts easier.
export UID="$(id -u)" &> /dev/null || true;
export GID="$(id -g)" &> /dev/null || true;

# Tell goenv where to install go, personally I prefer all my tools and
# config to be hidden (ie: start with a dot) and all my actual data
# folders/files to unhidden.
export GOENV_GOPATH_PREFIX="$HOME/.go";