#!/usr/bin/env bash
# .path - Set your PATH in here, this ensures PATH is idempotent.

PATH="/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin";
PATH="$PATH:$HOME/.local/bin";
PATH="$PATH:$HOME/.nodenv/bin";
PATH="$PATH:$HOME/.pyenv/bin";
PATH="$PATH:$HOME/.rbenv/bin";
PATH="$PATH:$HOME/.goenv/bin";
PATH="$PATH:$HOME/.tfenv/bin";