#!/usr/bin/env bash
set -euxo pipefail;
sudo dnf install -y gcc bzip2 openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel;
rm -rf ~/.rbenv;
git clone https://github.com/rbenv/rbenv.git ~/.rbenv;
cd ~/.rbenv && src/configure && make -C src && cd -;
mkdir -p ~/.rbenv/plugins;
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build;
rubyV="$(echo "$(~/.rbenv/bin/rbenv install --list)" | awk '{$1=$1};1' | grep '^[0-9]' | grep -v '[a-zA-Z]' | sed '/-/!{s/$/_/}' | sort -V | sed 's/_$//' | tail -n1)";
~/.rbenv/bin/rbenv install $rubyV;
~/.rbenv/bin/rbenv global $rubyV;
~/.rbenv/bin/rbenv rehash;