#!/usr/bin/env bash
set -euxo pipefail;
sudo dnf install -y jq tree bash-completion mlocate;

# ssh-agent/gpg-agent systemd user session
# git config - Work/Personal
# https://sdkman.io/
# https://dart.dev/
# https://github.com/phpbrew/phpbrew