#!/usr/bin/env bash
set -euxo pipefail;
rm -rf ~/.local/aws-cli ~/.local/bin/aws;
tmpFolder="/tmp/$(uuidgen)";
mkdir -p $tmpFolder;
function finish {
    rm -rf $tmpFolder;
}
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "$tmpFolder/awscliv2.zip";
unzip "$tmpFolder/awscliv2.zip" -d "$tmpFolder/extracted";
$tmpFolder/extracted/aws/install -i ~/.local/aws-cli -b ~/.local/bin;
~/.local/bin/aws --version;