#!/usr/bin/env bash
set -euxo pipefail;
rm -rf ~/.nodenv;
git clone https://github.com/nodenv/nodenv.git ~/.nodenv;
mkdir -p ~/.nodenv/plugins;
git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build;
git clone https://github.com/nodenv/nodenv-update.git ~/.nodenv/plugins/nodenv-update;
git clone https://github.com/nodenv/node-build-update-defs.git ~/.nodenv/plugins/node-build-update-defs;
cd ~/.nodenv && src/configure && make -C src && cd -;
nodeV="$(echo "$(~/.nodenv/bin/nodenv install --list)" | awk '{$1=$1};1' | grep '^[0-9]' | grep -v '[a-zA-Z]' | sed '/-/!{s/$/_/}' | sort -V | sed 's/_$//' | tail -n1)";
~/.nodenv/bin/nodenv install $nodeV;
~/.nodenv/bin/nodenv global $nodeV;
~/.nodenv/shims/npm install --global yarn;
~/.nodenv/shims/npm install --global pnpm;
~/.nodenv/bin/nodenv rehash;