#!/usr/bin/env bash
set -euxo pipefail;

# On desktop systems, ssh-agent is already taken care of for us.
# We only need to set this up on headless systems.
if [ -z "$XDG_SESSION_DESKTOP" ];
then
	sudo loginctl enable-linger $USER;
	systemctl --user daemon-reload;
	systemctl --user enable ssh-agent.service --now;
fi