#!/usr/bin/env bash
set -euxo pipefail;
sudo dnf install -y curl file git libxcrypt-compat;
rm -rf ~/.linuxbrew;
git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew;
mkdir ~/.linuxbrew/bin;
ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin;
eval "$(~/.linuxbrew/bin/brew shellenv)";
~/.linuxbrew/bin/brew --version;