version: '3'

silent: true
output: prefixed

vars:
  SHELL: '{{if eq OS "windows"}}powershell -Command{{end}}'
  SETUP: '{{if eq OS "windows"}}./bin/setup_windows_amd64.exe{{else}}./bin/setup_linux_amd64{{end}}'

tasks:
  apply:
    desc: Executes the setup binary in apply mode
    deps:
      - build
    cmds:
      - '{{.SETUP}} chezmoi-apply'

  build:
    desc: Builds binaries for Linux & Windows
    deps:
      - build-windows

  build-linux:
    desc: Builds the linux binary
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    sources:
      - ./**/*.go
    generates:
      - ./bin/setup_linux_amd64
    cmds:
      - go build -v -o ./bin/setup_linux_amd64

  build-windows:
    desc: Builds the windows binary
    deps:
      - build-linux
    env:
      CGO_ENABLED: 0
      GOOS: windows
      GOARCH: amd64
    sources:
      - ./**/*.go
    generates:
      - ./bin/setup_windows_amd64.exe
    cmds:
      - "{{.SHELL}} cp ./bin/setup_linux_amd64 ./tasks/steps/setup_linux_amd64"
      - go build -v -o ./bin/setup_windows_amd64.exe
      - "{{.SHELL}} rm ./tasks/steps/setup_linux_amd64"